image: kroggen/ubuntu-16.04-gcc

stages:
  - build

building:
  stage: build
  before_script:
    - wget https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz
    - tar -xf zig-x86_64-linux-0.15.2.tar.xz
    - export PATH="$PWD/zig-x86_64-linux-0.15.2:$PATH"
  script:
    - zig version
    - make
  artifacts:
    name: encp
    paths:
     - encp
